Various changed.
 * `gitflow.yml` is to be stored in `develop` branch.
 * Check whether `commit-msg` hook is installed by sending it a special
   parameter and checking stdout.

TODO: It might be safer to write to a file instead of stdout because that might
be used by other commit-msg webhooks the user has installed.

diff --git a/git-flow2-init b/git-flow2-init
--- a/git-flow2-init
+++ b/git-flow2-init
@@ -26,7 +26,16 @@ function mark_action_required {
   echo "${__bold}>>> Action required! <<< ${__normal}"
 }
 
-BRANCHES="develop master gitflow-config"
+function does_branch_exist {
+  local branch=$1
+  if git branch -a | grep -q -E "/?${branch}"; then
+    return 0
+  else
+    return 1
+  fi
+}
+
+BRANCHES="develop"
 
 start_spinner "Fetching from origin..."
 err=$(git fetch -a 2>&1 >/dev/null) || {
@@ -36,19 +45,24 @@ err=$(git fetch -a 2>&1 >/dev/null) || {
 }
 stop_spinner 0
 
+
 echo
 echored "Check Required Branches"
-echo "Making sure required branches exist: ${BRANCHES}"
+echo "Making sure required branches exist: master ${BRANCHES}"
+
+if ! does_branch_exist "master"; then
+  echo "${__bold}Oh noes, 'master' branch is missing!${__normal}"
+  print_scream
+  echo "I need master branch to exist."
+  echo "Please make sure there is one and run me again!"
+  exit 1
+fi
 
 for branch in ${BRANCHES}; do
   if ! git branch -a | grep -q -E "/?${branch}"; then
     echo
     echo "No branch '${branch}' found. Will create one for you for free."
-    current=$(git rev-parse --abbrev-ref HEAD)
-    git branch ${branch}
-    git symbolic-ref HEAD refs/heads/${branch}
-    git commit --allow-empty --message "Initial branch commit."
-    git checkout ${current} >/dev/null
+    git branch ${branch} master
     echo
   else
     echo -n "Branch '${branch}' found. "; print_checkmark
@@ -59,16 +73,12 @@ echo
 echo -n "Sweet, all the required branches exist! "; print_checkmark;
 
 echo
-echo "Checking out develop..."
-git checkout develop >/dev/null
-
-echo
 echored "Local Config"
 
-if ! git show gitflow-config:gitflow.yml 2>/dev/null >/dev/null; then
+if ! git show develop:gitflow.yml 2>/dev/null >/dev/null; then
   mark_action_required
   echo "Please make sure there's a 'pivotal_tracker' section with "
-  echo "'project_id: <PT PROJECT ID>' in 'gitflow.yml' file in branch 'gitflow-config'"
+  echo "'project_id: <PT PROJECT ID>' in 'gitflow.yml' file in branch 'develop'"
   echo "Example setting:"
   echo
   echo -e "  pivotal_tracker:\n    project_id: MY_PT_PROJECT_ID"
@@ -100,43 +110,37 @@ root="$(git rev-parse --show-toplevel)"
 hook_path="$root/.git/hooks/commit-msg"
 hook_executable="$(which git-flow2-commit-msg-hook)"
 
-if [ -e "$hook_path" ]; then
-  set +e
-  diff "$hook_path" "$hook_executable" 1>/dev/null
-  ret="$?"
-  set -e
-  if [ "$ret" -eq 2 ]; then
-    # Ask the user for confirmation.
-    echo "Your git commit-msg workflow hook is not up to date."
-    read -p "Shall we proceed and replace the current hook with the new one? [y/N]: " -n 1 -r
-    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
-      echo
-      mark_action_required
-      echo "I need the hook in order to do my job. So I will exit now."
-      exit 1
-    fi
-    echo
-    echo "Installing the workflow git commit-msg hook..."
-    echo
-    cp "$hook_executable" "$hook_path"
-    echo
-    echo -n "Git hook installed. "; print_checkmark
-  elif [ "$ret" -ne 0 ]; then
-    exit "$ret"
-  else
-    echo -n "Looks good. "; print_checkmark
-  fi
+if [[ ! -f "${hook_path}" ]]; then
+  test_output=""
 else
-  echo "Installing the workflow git commit-msg hook..."
-  cp "$hook_executable" "$hook_path"
-  echo
-  echo -n "Git hook installed. "; print_checkmark
+  test_output=$(eval "${hook_path}" "AreYouWhoIthinkYouAreHuh")
 fi
+
+if [[ "${test_output}" == "IAmGitFlowWebhookYaDoofus!" ]]; then
+  echo -n "Looks good. "; print_checkmark
+else
+  echo "We did not detect our webhook in your repo."
+  read -p "Shall we proceed and create or replace your current commit-msg hook with our GitFlow hook? [y/N]: " -n 1 -r
+  echo
+  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
+    mark_action_required
+    echo "I need the hook in order to do my job. So I will exit now."
+    echo "Please make sure '${hook_executable}' runs as your commit-msg hook and run me again!"
+  else
+    cp "$hook_executable" "$hook_path"
+    echo -n "Sweet, hook installed. "; print_checkmark
+  fi
+fi
+
+echo
+echored "Outcome"
 
 if [[ -n "${ACTION_REQUIRED}" ]]; then
   echo "Some required settings were not in place."
   echo "Please fix that and run me again!"
   exit 1
 else
+  echo "Everything is fine, repo is initialized!"
   git config ${GIT_CFG_INITIALIZED} true 
+  exit 0
 fi
